### ISSUE TITLE
Port in PHP

### ISSUE THREAD

**Issue by ghost** [gandreadis/markdown-word-count#3]
Hi,

I've ported this tool to PHP: https://github.com/Arcesilas/md-word-count

I've used MIT license. Since you don't specify any license, is it ok for you, or should I use another one?

Thanks for the tool!

**Comment by gandreadis** [comment]
Hi @Arcesilas, thanks for asking! That's great to hear :) 
I forgot to add a license, didn't expect this project to be widely used. I'm happy it is though :) 
The MIT license is fine, I'll also add it to this repo.
