### ISSUE TITLE
Second-level lists not counted

### ISSUE THREAD

**Issue by PraveshMoelchand** [gandreadis/markdown-word-count#5]
Hi,

Second-level items (red) in lists are not counted towards the total word count. The top-level items (red) are. This causes incorrect total word counts.

![afbeelding](https://user-images.githubusercontent.com/23723475/75679669-5cc9da80-5c90-11ea-8dea-c825ba02548d.png)

**Comment by gandreadis** [comment]
Hi, thanks for reporting! That's indeed an issue that I didn't think of, I'm opening a PR for it now :)
