### ISSUE TITLE
`>` in commented out quotes are seen as ending

### ISSUE THREAD

**Issue by PraveshMoelchand** [gandreadis/markdown-word-count#8]
Hi,

I'm not sure if we should just remove commented pieces of text, but when a quote is commented, the `>` at the beginning of the quote is seen as the ending of the comment, I believe comments can only be closed with `-->`.

In the example below "This is a quote" is included in the word count, even though it has been commented out.

```
<!-- > This is a quote -->
```

**Comment by gandreadis** [comment]
Hi, great work, that's indeed unwanted behavior! Thanks a lot :D

I've fixed this in a PR, see #10. Please don't hesitate to let me know if you find any other edge cases!
